# GitGuardian configuration
version: 2

# Paths to exclude from scanning
paths_ignore:
  - .git
  - node_modules
  - vendor

# Secrets detection settings
secret:
  # Ignore known secrets
  ignore_known_secrets: false
  
  # Minimum severity
  minimum_severity: medium
  
  # Show secrets in output (for debugging)
  show_secrets: false

# Enable all policies
all_policies: true
