name: Build and Deploy Blazor WebAssembly

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'wwwroot/**'
      - '*.csproj'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-blazor:
    uses: ./.github/workflows/reusable-dotnet-build.yml
    with:
      # .NET Configuration
      dotnet-version: '8.0.x'
      configuration: 'Release'
      
      # Project Settings
      project-path: 'src/BlazorApp/BlazorApp.csproj'
      
      # Build Options
      build-args: '-p:BlazorEnableCompression=true -p:BlazorWebAssemblyEnableLinking=true'
      
      # Testing with bUnit
      run-tests: true
      test-filter: 'Category!=E2E'
      
      # Publishing
      publish: true
      output-directory: './dist'
      publish-args: '-p:BlazorCacheBootResources=true -p:ServiceWorkerAssetsManifest=service-worker-assets.js'
      
      # Artifacts
      upload-artifacts: true
      artifact-name: 'blazor-app'
      artifact-path: './dist/wwwroot/**'
  
  deploy-github-pages:
    needs: build-blazor
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: dist
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Fix base href
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/${{ github.event.repository.name }}\/" \/>/g' dist/index.html
      
      - name: Add .nojekyll
        run: touch dist/.nojekyll
      
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
  
  deploy-azure-static-web:
    needs: build-blazor
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: azure
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: dist
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          output_location: ''
          skip_app_build: true