name: README Auto-Update (Reusable)

on:
  workflow_call:
    inputs:
      template-path:
        description: "Path to README template file"
        type: string
        default: "docs/README.template.MD"
      output-path:
        description: "Path to output README file"
        type: string
        default: "README.MD"
      python-version:
        description: "Python version to use"
        type: string
        default: "3.12"
      commit-message:
        description: "Commit message for README updates"
        type: string
        default: "docs(readme): auto-generate README [skip ci]"
      fail-on-pr:
        description: "Fail PR if README is out of date"
        type: boolean
        default: true
      auto-commit:
        description: "Auto-commit changes on workflow_dispatch"
        type: boolean
        default: true
      project-name:
        description: "Project name (overrides auto-detection)"
        type: string
        default: ""
      project-description:
        description: "Project description"
        type: string
        default: ""
      company-name:
        description: "Company name"
        type: string
        default: "BAUER GROUP"
      contact-email:
        description: "Contact email"
        type: string
        default: ""
      documentation-url:
        description: "Documentation URL"
        type: string
        default: ""
      support-url:
        description: "Support URL"
        type: string
        default: ""
    outputs:
      readme-updated:
        description: "Whether README was updated"
        value: ${{ jobs.generate-readme.outputs.readme-updated }}
      version-used:
        description: "Version used in README generation"
        value: ${{ jobs.generate-readme.outputs.version-used }}

permissions:
  contents: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    outputs:
      readme-updated: ${{ steps.readme.outputs.readme-updated }}
      version-used: ${{ steps.readme.outputs.version-used }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Generate README using Composite Action
        id: readme
        uses: bauer-group/automation-templates/.github/actions/readme-generate@main
        with:
          template-path: ${{ inputs.template-path }}
          output-path: ${{ inputs.output-path }}
          project-name: ${{ inputs.project-name }}
          company-name: ${{ inputs.company-name }}
          project-description: ${{ inputs.project-description }}
          auto-commit: ${{ inputs.auto-commit }}
          fail-on-pr: ${{ inputs.fail-on-pr }}

      - name: Summary
        run: |
          echo "## README Generation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Template**: ${{ inputs.template-path }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Output**: ${{ inputs.output-path }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.readme.outputs.version-used }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Updated**: ${{ steps.readme.outputs.readme-updated }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Event**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY