name: Security Scan (Reusable)

on:
  workflow_call:
    inputs:
      enable-codeql:
        type: boolean
        default: true
        description: "Run CodeQL analysis"
      enable-trivy:
        type: boolean
        default: false
        description: "Scan container with Trivy"

jobs:
  codeql:
    if: ${{ inputs.enable-codeql }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: javascript }
      - uses: github/codeql-action/analyze@v3

  trivy:
    if: ${{ inputs.enable-trivy }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: table
          exit-code: "1"
          ignore-unfixed: true
