name: 'Release Please'
description: 'Automatisches Release-Management mit Release-Please'
author: 'Bauer Group'

inputs:
  release-type:
    description: 'Release-Type (simple, node, python, etc.)'
    required: false
    default: 'simple'
  package-name:
    description: 'Package Name für Release'
    required: false
    default: ''
  bump-minor-pre-major:
    description: 'Bump minor pre-major'
    required: false
    default: 'true'
  bump-patch-for-minor-pre-major:
    description: 'Bump patch for minor pre-major'
    required: false
    default: 'true'
  token:
    description: 'GitHub Token'
    required: true

outputs:
  release_created:
    description: 'Whether a release was created'
    value: ${{ steps.release.outputs.release_created }}
  tag_name:
    description: 'The tag name of the release'
    value: ${{ steps.release.outputs.tag_name }}
  version:
    description: 'The version of the release'
    value: ${{ steps.release.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Release Please
      id: release
      uses: google-github-actions/release-please-action@v4
      with:
        release-type: ${{ inputs.release-type }}
        package-name: ${{ inputs.package-name }}
        bump-minor-pre-major: ${{ inputs.bump-minor-pre-major }}
        bump-patch-for-minor-pre-major: ${{ inputs.bump-patch-for-minor-pre-major }}
        token: ${{ inputs.token }}

    - name: Show Release Info
      if: steps.release.outputs.release_created
      shell: bash
      run: |
        echo "🎉 Release created!"
        echo "Tag: ${{ steps.release.outputs.tag_name }}"
        echo "Version: ${{ steps.release.outputs.version }}"

branding:
  icon: 'package'
  color: 'green'
