# Beispiel: Vollständige Pipeline mit README und Release
# Dieses Beispiel zeigt, wie beide Workflows zusammen verwendet werden

name: 🔄 Complete Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # README aktualisieren bei Änderungen am Template
  readme-update:
    if: contains(github.event.head_commit.modified, 'docs/README.template.MD') || github.event_name == 'workflow_dispatch'
    uses: bauer-group/automation-templates/github/workflows/readme.yml@main
    with:
      template-path: "docs/README.template.MD"
      output-path: "README.MD"
      project-name: "Mein Vollständiges Projekt"
      company-name: "Meine Firma"
      project-description: "Ein Beispielprojekt mit vollständiger CI/CD Pipeline"
      contact-email: "support@example.com"

  # Release nur bei Push auf main
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: readme-update  # README erst aktualisieren, dann Release
    uses: bauer-group/automation-templates/github/workflows/release-please.yml@main
    with:
      release-type: "simple"
      package-name: "mein-vollstaendiges-projekt"

  # Deployment oder weitere Aktionen nach erfolgreichem Release
  deploy:
    if: needs.release.outputs.release_created
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying version ${{ needs.release.outputs.version }}"
          # Hier würde das Deployment stattfinden
