name: 🚀 Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: bauer-group/automation-templates/github/workflows/release-please.yml@main
    with:
      release-type: "simple"  # oder "node", "python", etc.
      package-name: "mein-projekt"
      bump-minor-pre-major: true
      bump-patch-for-minor-pre-major: true

  # Optional: weitere Jobs nach Release
  post-release:
    if: needs.release.outputs.release_created
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Post-Release Actions
        run: |
          echo "Release ${{ needs.release.outputs.tag_name }} wurde erstellt!"
          # Hier könnten weitere Aktionen folgen (Deploy, Notifications, etc.)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: bauer-group/automation-templates/.github/actions/release-please@main
        with:
          target-branch: "main"
          release-type: "simple"
          direct-release: ${{ inputs.direct-release }}
          token: ${{ secrets.GITHUB_TOKEN }}
