name: Release Management Example

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      direct-release:
        description: "Create direct release without PR"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write  
  issues: write

jobs:
  release-please:
    name: Release Management
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: bauer-group/automation-templates/.github/actions/release-please@main
        with:
          target-branch: "main"
          release-type: "simple"
          direct-release: ${{ inputs.direct-release }}
          token: ${{ secrets.GITHUB_TOKEN }}
