# 🔔 Simple Teams Notifications Example
# Basic implementation of Teams notifications for common repository events
# Author: BAUER GROUP IT
# 
# This example demonstrates the simplest way to implement Teams notifications
# for the most common repository events without complex configuration.

name: Simple Teams Notifications

on:
  # Workflow completion events
  workflow_run:
    workflows: ["*"]
    types: [completed]
  
  # Issue events
  issues:
    types: [opened, closed]
  
  # Pull request events
  pull_request:
    types: [opened, closed]
  
  # Push to main branches
  push:
    branches: [main, master, develop]

permissions:
  contents: read
  issues: read
  pull-requests: read
  actions: read

jobs:
  # Simple workflow notifications
  workflow-notifications:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    name: 🔄 Simple Workflow Notifications
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔔 Success Notification
        if: github.event.workflow_run.conclusion == 'success'
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'workflow_success'
          title: '✅ Workflow Success'
          summary: 'Workflow **${{ github.event.workflow_run.name }}** completed successfully'

      - name: 🔔 Failure Notification
        if: github.event.workflow_run.conclusion == 'failure'
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'workflow_failure'
          title: '❌ Workflow Failed'
          summary: 'Workflow **${{ github.event.workflow_run.name }}** failed'
          mention-users: 'devops-team'

  # Simple issue notifications
  issue-notifications:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    name: 🐛 Simple Issue Notifications
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔔 Issue Opened
        if: github.event.action == 'opened'
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'issue_opened'
          title: '🐛 New Issue'
          summary: '**#${{ github.event.issue.number }}**: ${{ github.event.issue.title }}'
          issue-number: ${{ github.event.issue.number }}
          issue-url: ${{ github.event.issue.html_url }}

      - name: 🔔 Issue Closed
        if: github.event.action == 'closed'
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'issue_closed'
          title: '✅ Issue Closed'
          summary: '**#${{ github.event.issue.number }}**: ${{ github.event.issue.title }}'
          issue-number: ${{ github.event.issue.number }}
          issue-url: ${{ github.event.issue.html_url }}

  # Simple PR notifications
  pr-notifications:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: 🔀 Simple PR Notifications
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔔 PR Opened
        if: github.event.action == 'opened'
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'pr_opened'
          title: '🔀 New Pull Request'
          summary: '**#${{ github.event.pull_request.number }}**: ${{ github.event.pull_request.title }}'
          pr-number: ${{ github.event.pull_request.number }}
          pr-url: ${{ github.event.pull_request.html_url }}

      - name: 🔔 PR Merged
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'pr_merged'
          title: '🎉 PR Merged'
          summary: '**#${{ github.event.pull_request.number }}**: ${{ github.event.pull_request.title }}'
          pr-number: ${{ github.event.pull_request.number }}
          pr-url: ${{ github.event.pull_request.html_url }}

  # Simple push notifications
  push-notifications:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: 🚀 Simple Push Notifications
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔔 Push Notification
        uses: bauer-group/automation-templates/.github/actions/teams-notification@main
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          event-type: 'push'
          title: '🚀 Code Pushed'
          summary: 'New commits pushed to **${{ github.ref_name }}**'