# Enterprise Docker Configuration
# Maximum security, compliance, and monitoring for enterprise environments

docker:
  # Build Configuration
  dockerfile: "./Dockerfile"
  context: "."
  target: "production"
  
  # Multi-platform for enterprise cloud deployment
  platforms: "linux/amd64,linux/arm64"
  multi_platform: true
  
  # Registry Configuration (enterprise registry)
  registry: "enterprise-registry.company.com"
  auto_tags: true
  latest_tag: false  # Disable latest in enterprise
  push_on_pr: false

# Build Arguments for enterprise
build_args:
  BUILDTIME: ""
  VERSION: ""
  ENVIRONMENT: "production"
  COMPLIANCE_MODE: "enabled"
  AUDIT_LOGGING: "enabled"
  ENCRYPTION: "enabled"

# Enterprise caching strategy
cache:
  enabled: true
  mode: "max"
  registry: "enterprise-registry.company.com/cache"

# Maximum Security Configuration
security:
  scan_enabled: true
  scanner: "trivy"
  fail_on: "MEDIUM"  # Stricter for enterprise
  ignore_unfixed: false
  sign_image: true
  generate_sbom: true
  sbom_format: "spdx"
  
  # Additional enterprise security
  vulnerability_database: "enterprise"
  compliance_scanning: true
  secret_scanning: true
  license_scanning: true

# Comprehensive testing for enterprise
testing:
  pre_build: true
  post_build: true
  test_command: "docker run --rm $IMAGE_TAG test --enterprise"
  integration_tests: true
  contract_tests: true
  security_tests: true
  performance_tests: true
  compliance_tests: true

# Enterprise performance configuration
performance:
  builder_driver: "kubernetes"
  build_timeout: 60
  parallel_builds: true
  build_attestation: true

# Enterprise compliance labels
labels:
  add_git_labels: true
  custom_labels:
    "org.opencontainers.image.title": "Enterprise Application"
    "org.opencontainers.image.vendor": "Company Name"
    "org.opencontainers.image.compliance": "SOC2,HIPAA,PCI-DSS"
    "security.scan.date": ""
    "security.scan.status": ""
    "compliance.approved": "true"
    "app.criticality": "high"
    "app.environment": "production"
    "backup.required": "true"
    "monitoring.required": "true"

# Enterprise deployment configuration
deployment:
  enabled: true
  environment: "production"
  command: "kubectl apply -f k8s/enterprise/ --dry-run=server"
  approval_required: true
  
# Governance and compliance
governance:
  policy_enforcement: true
  admission_controller: "OPA"
  network_policies: true
  pod_security_standards: "restricted"

# Enterprise monitoring
monitoring:
  full_observability: true
  apm_enabled: true
  log_aggregation: "splunk"
  metrics_system: "prometheus"
  alerting: "pagerduty"
  sla_monitoring: true

# Backup and disaster recovery
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: "90d"
  cross_region: true

# Audit and compliance
audit:
  enabled: true
  log_level: "detailed"
  retention: "7y"
  compliance_reports: true
  
# Resource specifications (enterprise grade)
resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
  
# High availability configuration
availability:
  replicas: 3
  anti_affinity: true
  pod_disruption_budget: true
  health_checks:
    liveness_probe: true
    readiness_probe: true
    startup_probe: true