name: Build Class Library

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '*.csproj'
      - '*.sln'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet-version: '8.0.x'
      project-path: 'src/MyLibrary.csproj'
      configuration: 'Release'
      run-tests: true
      create-package: true
      upload-artifacts: true
      artifact-name: 'my-library'