# Example: Simple Python Application CI
# This example demonstrates using the reusable Python build workflow for a basic application

name: Python Application CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    name: Build & Test Application
    uses: ./.github/workflows/python-build.yml
    with:
      # Basic Configuration
      python-version: "3.12"
      working-directory: "."
      project-type: "app"

      # Dependencies
      requirements-files: '["requirements.txt", "requirements-dev.txt"]'
      install-dev-requirements: true
      package-manager: "pip"
      cache-dependencies: true

      # Testing
      run-tests: true
      test-framework: "pytest"
      test-path: "tests"
      collect-coverage: true
      coverage-threshold: 80
      coverage-format: "xml,html"

      # Code Quality
      run-lint: true
      linter: "flake8"
      max-line-length: 127
      run-format-check: false
      run-type-check: false

      # Security
      run-security-scan: true
      security-tools: '["bandit", "safety"]'
      security-fail-on-error: false

      # Artifacts
      upload-artifacts: true
      artifact-name: "python-app"

    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Optional: Deploy to staging after successful build
  deploy-staging:
    name: Deploy to Staging
    needs: build
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com

    steps:
      - name: Deploy Application
        run: |
          echo "Deploying Python application to staging..."
          # Add your deployment commands here
          # Example: kubectl, docker, rsync, etc.

  # Optional: Deploy to production after successful build on main
  deploy-production:
    name: Deploy to Production
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com

    steps:
      - name: Deploy Application
        run: |
          echo "Deploying Python application to production..."
          # Add your deployment commands here
