# Example: Python Package CI with Multi-Platform Testing
# This example demonstrates using the reusable Python build workflow for PyPI packages

name: Python Package CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    name: Build & Test Package
    uses: ./.github/workflows/python-build.yml
    with:
      # Matrix Configuration for multi-platform testing
      enable-matrix: true
      matrix-os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      matrix-python: '["3.9", "3.10", "3.11", "3.12"]'
      matrix-fail-fast: false
      
      # Basic Configuration
      working-directory: '.'
      project-type: 'package'
      
      # Dependencies
      requirements-files: '["requirements.txt", "requirements-dev.txt"]'
      install-dev-requirements: true
      package-manager: 'pip'
      cache-dependencies: true
      
      # Testing
      run-tests: true
      test-framework: 'pytest'
      test-path: 'tests'
      collect-coverage: true
      coverage-threshold: 90
      coverage-format: 'xml,html'
      coverage-fail-under: false
      
      # Code Quality
      run-lint: true
      linter: 'ruff'
      run-format-check: true
      formatter: 'black'
      format-check-only: true
      run-import-sort: true
      run-type-check: true
      type-checker: 'mypy'
      
      # Security
      run-security-scan: true
      security-tools: '["bandit", "safety"]'
      security-fail-on-error: false
      
      # Package Building
      build-package: true
      build-tools: '["build", "twine"]'
      package-check: true
      
      # Artifacts
      upload-artifacts: true
      artifact-name: 'python-package'
      
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Optional: Publish to TestPyPI on develop branch
  publish-test:
    name: Publish to TestPyPI
    needs: build
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    uses: ./.github/workflows/python-publish.yml
    with:
      python-version: '3.11'
      publish-to: 'testpypi'
      run-tests: false  # Already tested in build job
      validate-package: true
      run-security-scan: true
      create-github-release: false
      environment: 'testpypi'
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Optional: Publish to PyPI on release
  publish-release:
    name: Publish to PyPI
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/python-publish.yml
    with:
      python-version: '3.11'
      publish-to: 'pypi'
      run-tests: false  # Already tested in build job
      validate-package: true
      run-security-scan: true
      create-github-release: true
      release-draft: false
      release-prerelease: false
      generate-docs: true
      environment: 'pypi'
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}