# STM32 Industrial Release Pipeline Example
# Secure release pipeline for safety-critical applications
#
# Use case: Industrial, automotive, medical applications
# Features: MISRA compliance, full analysis, approval gates

name: STM32 Industrial Release

on:
  push:
    tags: ['v*']

  workflow_dispatch:
    inputs:
      target-mcu:
        description: 'Target MCU'
        required: true
        default: 'STM32F407VG'
        type: choice
        options:
          - STM32F407VG
          - STM32F446RE
          - STM32H743ZI

      dry-run:
        description: 'Dry run (no release)'
        required: false
        default: true
        type: boolean

jobs:
  # Compliance checks
  compliance:
    name: Compliance Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: License Compliance
        uses: bauer-group/automation-templates/.github/actions/license-compliance@main
        with:
          check-headers: true
          allowed-licenses: 'Apache-2.0,MIT,BSD-3-Clause'
          fail-on-violation: true

      - name: Security Scan
        uses: bauer-group/automation-templates/.github/actions/security-scan@main
        with:
          scan-engines: 'gitleaks'
          fail-on-findings: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Main build with full analysis
  build:
    name: Industrial Build
    needs: compliance
    uses: bauer-group/automation-templates/.github/workflows/stm32-build.yml@main
    with:
      # Industrial configuration
      config-file: industrial

      # Target MCU
      target-mcu: ${{ inputs.target-mcu || 'STM32F407VG' }}

      # Both build types for validation
      build-types: '["Release", "Debug"]'

      # Full testing
      run-tests: true
      test-framework: unity

      # Full static analysis
      enable-analysis: true

      # MISRA compliance
      enable-misra: true

      # All output formats
      create-hex: true
      create-bin: true

      # Create release (unless dry run)
      create-release: ${{ !inputs.dry-run && github.event_name == 'push' }}

      # Long retention for compliance
      artifact-retention: 365

      # All builds must succeed
      fail-fast: true

      # Extended timeout
      timeout-minutes: 60

  # Quality gate validation
  quality-gate:
    name: Quality Gate
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
          pattern: stm32-*

      - name: Validate build outputs
        run: |
          echo "=== Quality Gate Validation ==="

          # Check firmware exists
          FIRMWARE=$(find artifacts -name "*.bin" -type f | head -1)
          if [[ -z "$FIRMWARE" ]]; then
            echo "ERROR: No firmware binary found"
            exit 1
          fi
          echo "Firmware binary found: $FIRMWARE"

          # Check firmware size
          FIRMWARE_SIZE=$(stat -c%s "$FIRMWARE" 2>/dev/null || stat -f%z "$FIRMWARE")
          MAX_SIZE=524288  # 512KB
          if [[ $FIRMWARE_SIZE -gt $MAX_SIZE ]]; then
            echo "ERROR: Firmware too large: $FIRMWARE_SIZE > $MAX_SIZE"
            exit 1
          fi
          echo "Firmware size OK: $FIRMWARE_SIZE bytes"

          # Check for analysis reports
          ANALYSIS=$(find artifacts -name "cppcheck-report.xml" -type f | head -1)
          if [[ -n "$ANALYSIS" ]]; then
            echo "Static analysis report found"
          fi

          echo ""
          echo "=== Quality Gate PASSED ==="

      - name: Generate compliance report
        run: |
          cat > compliance-report.md << 'EOF'
          # Industrial Firmware Compliance Report

          ## Build Information
          - **Version**: ${{ github.ref_name }}
          - **Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - **Commit**: ${{ github.sha }}
          - **Target MCU**: ${{ inputs.target-mcu || 'STM32F407VG' }}

          ## Compliance Status
          - **License Check**: PASSED
          - **Security Scan**: PASSED
          - **Build Validation**: PASSED
          - **Static Analysis**: PASSED
          - **MISRA Check**: PASSED

          ## Artifacts
          - Release firmware (BIN, HEX, ELF)
          - Debug firmware with symbols
          - Static analysis report
          - MISRA compliance report
          - Size analysis

          ---
          Generated by Industrial Release Pipeline
          EOF

      - name: Upload compliance report
        uses: actions/upload-artifact@v6
        with:
          name: compliance-report
          path: compliance-report.md
          retention-days: 365

  # Manual approval for production
  approval:
    name: Release Approval
    needs: quality-gate
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Approval confirmed
        run: |
          echo "Release approved for production"
          echo "Version: ${{ github.ref_name }}"

  # Notify on completion
  notify:
    name: Notify
    needs: [build, quality-gate]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          VERSION="${{ github.ref_name }}"
          BUILD_STATUS="${{ needs.build.result }}"
          QG_STATUS="${{ needs.quality-gate.result }}"

          echo "Industrial Release $VERSION"
          echo "Build: $BUILD_STATUS"
          echo "Quality Gate: $QG_STATUS"

          if [[ "$BUILD_STATUS" == "success" && "$QG_STATUS" == "success" ]]; then
            echo "Release pipeline completed successfully"
          else
            echo "Release pipeline failed"
            exit 1
          fi
