# Meta Repository Sync with Notifications
#
# This advanced configuration includes:
# - Microsoft Teams notifications
# - Error handling and retry logic
# - Detailed reporting
# - Integration with other workflows
#
# Requirements:
# - TEAMS_WEBHOOK_URL secret configured
# - teams-notifications workflow available

name: 🔄 Sync with Notifications

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-from-repository]
  schedule:
    - cron: "45 23 * * 6"

permissions:
  contents: write
  actions: read

jobs:
  sync:
    name: Sync Repositories
    uses: bauer-group/automation-templates/.github/workflows/meta-repository-sync.yml@main
    with:
      config-file: '.github/config/meta-repository/topics.json'
      generate-readme: true
      generate-json: true
      generate-txt: true
      auto-commit: true

  notify-success:
    name: Notify Success
    needs: sync
    if: success()
    uses: bauer-group/automation-templates/.github/workflows/teams-notifications.yml@main
    with:
      webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
      title: "✅ Meta Repository Sync Successful"
      message: |
        **Summary:** ${{ needs.sync.outputs.sync-summary }}
        **Repositories:** ${{ needs.sync.outputs.repositories-synced }}

        The meta repository has been successfully synchronized.
      color: "good"
      facts: |
        [
          {
            "name": "Repository",
            "value": "${{ github.repository }}"
          },
          {
            "name": "Triggered By",
            "value": "${{ github.event_name }}"
          },
          {
            "name": "Repositories Synced",
            "value": "${{ needs.sync.outputs.repositories-synced }}"
          }
        ]

  notify-failure:
    name: Notify Failure
    needs: sync
    if: failure()
    uses: bauer-group/automation-templates/.github/workflows/teams-notifications.yml@main
    with:
      webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
      title: "❌ Meta Repository Sync Failed"
      message: |
        The meta repository synchronization has failed.

        Please check the workflow logs for details.
      color: "attention"
      facts: |
        [
          {
            "name": "Repository",
            "value": "${{ github.repository }}"
          },
          {
            "name": "Workflow Run",
            "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
        ]

  create-issue-on-failure:
    name: Create Issue on Failure
    needs: sync
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔄 Meta Repository Sync Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `## Sync Failure Report

              The automated meta repository synchronization has failed.

              **Details:**
              - Workflow Run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
              - Triggered By: ${context.eventName}
              - Time: ${new Date().toISOString()}

              **Action Required:**
              1. Review the workflow logs
              2. Check configuration file validity
              3. Verify GitHub token permissions
              4. Manually trigger sync after fixing issues

              This issue was automatically created by the sync workflow.`,
              labels: ['automation', 'sync-failure', 'bug']
            });

            console.log(`Created issue #${issue.data.number}`);
