name: Build WPF Application

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - '*.sln'
      - '*.csproj'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.sln'
      - '*.csproj'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-dotnet-desktop-build.yml
    with:
      dotnet-version: '8.0.x'
      configurations: '["Release"]'
      platforms: '["x64"]'
      solution-path: 'src/MyWpfApp.sln'
      publish-type: 'self-contained'
      run-tests: true
      upload-artifacts: true
      artifact-name: 'wpf-app'