# ============================================================================
# Simple Coolify Deployment (REST API)
# ============================================================================
# This example demonstrates the minimal configuration for deploying
# an application to Coolify via the REST API. The deployment is triggered
# on every push to the main branch using a "fire and forget" approach.
#
# NOTE: This uses the Coolify REST API, not the GitHub App webhooks.
# If you have the Coolify GitHub App with Auto Deploy enabled, you don't
# need this workflow - deployments happen automatically on push.
#
# Features:
# - Minimal configuration
# - Triggers on push to main
# - No wait for completion (fastest)
#
# Prerequisites:
# - REST API enabled in Coolify (Settings)
# - API Token created in Coolify (Security > API Tokens)
# - COOLIFY_API_TOKEN secret configured in GitHub
# - Application already set up in Coolify
# ============================================================================

name: Deploy to Coolify

on:
  push:
    branches: [main]

  # Allow manual deployment
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: bauer-group/automation-templates/.github/workflows/coolify-deploy.yml@main
    with:
      coolify-url: 'https://coolify.example.com'
      app-uuid: 'your-app-uuid-here'
    secrets: inherit
