# Linux Kernel Module Configuration
# =================================
# Configuration for building Linux kernel modules

name: "Kernel Module Build"
description: "Configuration for Linux kernel module development"

# Build Environment
environment:
  # System dependencies for kernel development
  dependencies:
    ubuntu:
      - build-essential
      - linux-headers-generic
      - kmod
      - bc
      - bison
      - flex
      - libssl-dev
      - libelf-dev
    
    fedora:
      - "@development-tools"
      - kernel-devel
      - kernel-headers
      - kmod
      - bc
      - bison
      - flex
      - openssl-devel
      - elfutils-libelf-devel
    
    # Note: macOS doesn't support kernel module development
    macos: []

# Configure Stage
configure:
  script: ""  # No configure script for kernel modules
  args: []
  generate_if_missing: false
  cache_enabled: false

# Build Stage
build:
  targets: ["modules"]
  parallel_jobs: "auto"
  make_args:
    - "KDIR=/lib/modules/$(shell uname -r)/build"
    - "M=$(PWD)"
  fail_on_warnings: false
  
  # Kernel build environment
  env:
    KBUILD_VERBOSE: "1"

# Test Stage
test:
  enabled: true
  targets: ["modules_check"]
  parallel: false
  continue_on_error: false
  
  # Custom test commands
  custom_commands:
    - "modinfo *.ko"
    - "checkpatch.pl --no-tree -f *.c *.h || true"
  
  # Test environment
  env:
    KERNELDIR: "/lib/modules/$(shell uname -r)/build"

# Distribution Check
distcheck:
  enabled: false
  target: ""
  timeout_minutes: 0

# Installation Test
install:
  enabled: false
  targets: ["modules_install"]
  requires_root: true

# Artifacts
artifacts:
  enabled: true
  paths:
    # Kernel module artifacts
    - "*.ko"
    - "*.mod"
    - "*.mod.c"
    - "*.o"
    - "Module.symvers"
    - "modules.order"
    - ".*.cmd"
    
    # Build logs
    - "**/*.log"
    
    # Debug symbols
    - "*.ko.debug"
  
  # Test results
  test_results:
    - "checkpatch.log"
    - "modinfo.log"

# Caching
cache:
  enabled: true
  paths:
    - "~/.cache/"
    - ".tmp_versions/"
  
  key_files:
    - "Makefile"
    - "Kbuild"
    - "*.c"
    - "*.h"

# Quality Settings
quality:
  warnings_as_errors: false
  static_analysis: true
  code_coverage: false
  
  # Kernel-specific quality checks
  kernel_checks:
    - "sparse"
    - "checkpatch"
    - "coccinelle"
  
  # Static analysis tools
  static_tools:
    - "sparse"
    - "smatch"

# Documentation
documentation:
  generate: false
  formats: []

# Kernel-specific settings
kernel:
  # Supported kernel versions
  min_version: "4.4"
  max_version: "6.x"
  
  # Module parameters
  module_info:
    license: "GPL"
    author: "Your Name"
    description: "Kernel module description"
    version: "1.0"
  
  # Security options
  security:
    signed_modules: false
    lockdown_check: true