name: 'Semantic Release'
description: 'Automated semantic versioning and release creation with changelog generation'
author: 'BAUER GROUP'

inputs:
  dry-run:
    description: 'Run in dry-run mode without creating release'
    required: false
    default: 'false'
  branches:
    description: 'Branches to release from (JSON array or single branch)'
    required: false
    default: 'main'
  extra-plugins:
    description: 'Extra semantic-release plugins to install'
    required: false
    default: ''
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  token:
    description: 'GitHub token for authentication'
    required: true
  force-release:
    description: 'Force create release even without conventional commits'
    required: false
    default: 'false'

outputs:
  release-created:
    description: 'Whether a release was created'
    value: ${{ steps.release.outputs.new_release_published }}
  version:
    description: 'The new version'
    value: ${{ steps.release.outputs.new_release_version }}
  tag:
    description: 'The git tag'
    value: ${{ steps.tag.outputs.tag }}
  changelog:
    description: 'The changelog for this release'
    value: ${{ steps.release.outputs.new_release_notes }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Build Config
      shell: bash
      run: |
        echo "Building semantic-release config..."

        # Default release rules
        DEFAULT_RULES='[
          {"breaking": true, "release": "major"},
          {"type": "feat", "release": "minor"},
          {"type": "fix", "release": "patch"},
          {"type": "perf", "release": "patch"},
          {"type": "revert", "release": "patch"},
          {"type": "refactor", "release": "patch"}
        ]'

        FORCE_RULES='[
          {"breaking": true, "release": "major"},
          {"type": "feat", "release": "minor"},
          {"type": "fix", "release": "patch"},
          {"type": "perf", "release": "patch"},
          {"type": "revert", "release": "patch"},
          {"type": "refactor", "release": "patch"},
          {"type": "docs", "release": "patch"},
          {"type": "style", "release": "patch"},
          {"type": "chore", "release": "patch"},
          {"type": "test", "release": "patch"},
          {"type": "build", "release": "patch"},
          {"type": "ci", "release": "patch"},
          {"message": "*", "release": "patch"}
        ]'

        # Check for repo-specific config to merge
        EXTRA_PLUGINS="[]"
        CHANGELOG_FILE="CHANGELOG.md"
        GIT_ASSETS='["CHANGELOG.md"]'
        GIT_MESSAGE='"chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"'
        RELEASE_RULES=""

        if [ -f ".github/config/release/semantic-release.json" ]; then
          echo "Found repository config - extracting custom settings..."
          REPO_CONFIG=".github/config/release/semantic-release.json"

          # Extract releaseRules if specified (REPLACES default rules)
          CUSTOM_RULES=$(jq -c '.plugins[] | select(type == "array") | select(.[0] == "@semantic-release/commit-analyzer") | .[1].releaseRules // empty' "$REPO_CONFIG" 2>/dev/null || echo "")
          if [ -n "$CUSTOM_RULES" ] && [ "$CUSTOM_RULES" != "null" ] && [ "$CUSTOM_RULES" != "[]" ]; then
            RELEASE_RULES="$CUSTOM_RULES"
            echo "  Using custom releaseRules from repo config"
          fi

          # Extract changelog file path if specified
          CUSTOM_CHANGELOG=$(jq -r '.plugins[] | select(type == "array") | select(.[0] == "@semantic-release/changelog") | .[1].changelogFile // empty' "$REPO_CONFIG" 2>/dev/null || echo "")
          if [ -n "$CUSTOM_CHANGELOG" ]; then
            CHANGELOG_FILE="$CUSTOM_CHANGELOG"
            echo "  Using custom changelog: $CHANGELOG_FILE"
          fi

          # Extract git assets if specified
          CUSTOM_ASSETS=$(jq -c '.plugins[] | select(type == "array") | select(.[0] == "@semantic-release/git") | .[1].assets // empty' "$REPO_CONFIG" 2>/dev/null || echo "")
          if [ -n "$CUSTOM_ASSETS" ] && [ "$CUSTOM_ASSETS" != "null" ]; then
            GIT_ASSETS="$CUSTOM_ASSETS"
            echo "  Using custom git assets: $GIT_ASSETS"
          fi

          # Extract git message if specified (keep as JSON string to preserve escapes)
          CUSTOM_MESSAGE=$(jq '.plugins[] | select(type == "array") | select(.[0] == "@semantic-release/git") | .[1].message // empty' "$REPO_CONFIG" 2>/dev/null || echo "null")
          if [ "$CUSTOM_MESSAGE" != "null" ] && [ "$CUSTOM_MESSAGE" != '""' ] && [ -n "$CUSTOM_MESSAGE" ]; then
            GIT_MESSAGE="$CUSTOM_MESSAGE"
            echo "  Using custom git message"
          fi

          # Extract extra plugins (not commit-analyzer, release-notes-generator, changelog, git, github)
          EXTRA_PLUGINS=$(jq -c '[.plugins[] | select(
            (type == "string" and . != "@semantic-release/commit-analyzer" and . != "@semantic-release/release-notes-generator" and . != "@semantic-release/changelog" and . != "@semantic-release/git" and . != "@semantic-release/github") or
            (type == "array" and .[0] != "@semantic-release/commit-analyzer" and .[0] != "@semantic-release/release-notes-generator" and .[0] != "@semantic-release/changelog" and .[0] != "@semantic-release/git" and .[0] != "@semantic-release/github")
          )]' "$REPO_CONFIG" 2>/dev/null || echo "[]")

          if [ "$EXTRA_PLUGINS" != "[]" ] && [ "$EXTRA_PLUGINS" != "null" ]; then
            echo "  Found extra plugins: $EXTRA_PLUGINS"
          else
            EXTRA_PLUGINS="[]"
          fi
        else
          echo "No repository config found - using defaults"
        fi

        # Determine final release rules
        if [ -n "$RELEASE_RULES" ]; then
          echo "Using: custom releaseRules from repo"
        elif [ "${{ inputs.force-release }}" = "true" ]; then
          echo "Using: force-release rules (all commit types trigger release)"
          RELEASE_RULES="$FORCE_RULES"
        else
          echo "Using: standard releaseRules (feat/fix/perf/revert/refactor)"
          RELEASE_RULES="$DEFAULT_RULES"
        fi

        # Build the final config
        cat > .releaserc.json << EOF
        {
          "branches": ["${{ inputs.branches }}"],
          "plugins": [
            ["@semantic-release/commit-analyzer", {
              "preset": "conventionalcommits",
              "releaseRules": $RELEASE_RULES
            }],
            ["@semantic-release/release-notes-generator", {
              "preset": "conventionalcommits",
              "presetConfig": {
                "types": [
                  {"type": "feat", "section": "ðŸš€ Features"},
                  {"type": "fix", "section": "ðŸ› Bug Fixes"},
                  {"type": "perf", "section": "âš¡ Performance"},
                  {"type": "revert", "section": "âª Reverts"},
                  {"type": "refactor", "section": "â™»ï¸ Refactoring"},
                  {"type": "docs", "section": "ðŸ“š Documentation", "hidden": true},
                  {"type": "style", "section": "ðŸ’„ Styles", "hidden": true},
                  {"type": "chore", "section": "ðŸ”§ Chores", "hidden": true},
                  {"type": "test", "section": "ðŸ§ª Tests", "hidden": true},
                  {"type": "build", "section": "ðŸ”¨ Build", "hidden": true},
                  {"type": "ci", "section": "ðŸ‘· CI", "hidden": true}
                ]
              }
            }],
            ["@semantic-release/changelog", {
              "changelogFile": "$CHANGELOG_FILE"
            }],
            ["@semantic-release/git", {
              "assets": $GIT_ASSETS,
              "message": $GIT_MESSAGE
            }],
            "@semantic-release/github"
          ]
        }
        EOF

        # Merge extra plugins if any
        if [ "$EXTRA_PLUGINS" != "[]" ]; then
          echo "Merging extra plugins into config..."
          # Insert extra plugins before @semantic-release/github
          jq --argjson extra "$EXTRA_PLUGINS" '
            .plugins = [.plugins[0], .plugins[1], .plugins[2]] + $extra + [.plugins[3], .plugins[4]]
          ' .releaserc.json > .releaserc.tmp.json && mv .releaserc.tmp.json .releaserc.json
        fi

        echo ""
        echo "Final config:"
        cat .releaserc.json | jq .

    - name: Semantic Release
      id: release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        dry_run: ${{ inputs.dry-run }}
        branches: ${{ inputs.branches }}
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          conventional-changelog-conventionalcommits
          ${{ inputs.extra-plugins }}

    - name: Set Tag Output
      id: tag
      shell: bash
      if: steps.release.outputs.new_release_published == 'true'
      run: |
        echo "tag=v${{ steps.release.outputs.new_release_version }}" >> $GITHUB_OUTPUT

branding:
  icon: 'package'
  color: 'green'