name: 🤖 Issue AI Summary

# Automatically summarize new issues and PRs using AI
# This workflow uses the modular AI summary component

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read
  models: read

jobs:
  summarize-new-issue:
    name: Generate AI Summary
    if: github.event_name == 'issues' || github.event_name == 'pull_request_target'
    uses: ./.github/workflows/modules-ai-issue-summary.yml
    with:
      summary-type: 'brief'           # Options: brief, detailed, technical, user-friendly
      add-labels: true                # Add suggested labels based on AI analysis
      add-priority: true               # Add priority labels based on AI analysis
      translate: ''                   # Leave empty or specify language (e.g., 'German', 'Spanish')
      model: 'gpt-4o'                 # AI model to use
      comment-template: |
        ## 🤖 AI Summary
        
        {summary}
        
        ---
        *This summary was automatically generated by AI to help with triage and may not be 100% accurate.*
    secrets: inherit
