name: Create Release

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
  workflow_dispatch:
    inputs:
      direct-release:
        description: "Create direct release without PR"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write  
  issues: write

jobs:
  release-please:
    name: Release Management
    if: |
      (github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore(main): release')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: ./.github/actions/release-please
        with:
          target-branch: "main"
          release-type: "simple"
          direct-release: ${{ inputs.direct-release }}
          config-file: ".github/config/release-please-config.json"
          manifest-file: ".github/config/.release-please-manifest.json"
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
