name: Create Release

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
  workflow_dispatch:
    inputs:
      direct-release:
        description: "Create direct release without PR"
        type: boolean
        default: false
      package-name:
        description: "Override package name (optional)"
        type: string
        default: ""

permissions:
  contents: write
  pull-requests: write  
  issues: write

jobs:
  release-please:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      github.event_name == 'workflow_dispatch'    
    uses: ./github/workflows/release-please.yml
    with:
      target-branch: "main"
      package-name: ${{ inputs.package-name || 'automation-templates' }}
      release-type: "simple"
      direct-release: ${{ inputs.direct-release || false }}
      config-file: ".github/config/release-please-config.json"
      manifest-file: ".github/config/.release-please-manifest.json"
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
